@startuml
hide empty description

[*] --> サインイン
サインイン: メールアドレス、パスワードを入力
サインイン --> サインイン: 失敗
サインイン --> サインイン済み: 成功

サインイン --> サインアップ: アカウントをお持ちでない場合
サインイン --> パスワードリセット: パスワードを忘れた場合

サインアップ: ユーザID、表示名、メールアドレス、パスワードを入力
サインアップ --> メール認証: ユーザID,メールアドレスが使われていない。
メール認証: 認証トークンを入力
メール認証 --> メール認証: 失敗
メール認証 --> サインイン済み: 成功

パスワードリセット: メールアドレス、トークンを入力
パスワードリセット --> パスワードリセット: 失敗
パスワードリセット --> サインイン: 成功

state サインイン済み {
    
    ' 単体画面の宣言
    state ブログ
    state 検索
    state "フッターメニュー" as フッター

    ' ダッシュボードグループの構造
    state ダッシュボード {
        state "チャット" as Chat
        state "グループ編集" as GroupEdit
        state "グループ作成" as GroupCreate
        
        GroupEdit: 名前、アイコン、権限編集、追加、退会、グループ削除

        [*] --> Chat
        [*] --> GroupCreate
    }

    ' プロフィールグループの構造
    state プロフィール {
        state 自分: 自分のプロフィール,編集
        state 他人: ブロック、チャット開始

        [*] --> 自分
        [*] --> 他人
    }

    ' ブロググループの構造
    state ブログ {
        state 公開ブログ一覧
        state 非公開ブログ一覧
        state ブログ詳細
        state ブログ作成
        state ブログ編集

        [*] --> 公開ブログ一覧
        [*] --> 非公開ブログ一覧
        [*] --> ブログ作成
    }

    [*] -right-> ダッシュボード
}

' --- 遷移の定義 ---

' ダッシュボード
Chat --> GroupEdit
Chat --> ブログ
Chat --> プロフィール
GroupCreate --> ダッシュボード: 成功
GroupCreate --> GroupCreate: 失敗
GroupEdit --> GroupEdit: 編集

' プロフィール内部・外部への遷移
自分 --> 自分: 編集
自分 --> サインイン: サインアウト
他人 --> Chat: チャット開始

' フッターからの遷移
フッター -up-> ダッシュボード
フッター -up-> ブログ
フッター -up-> プロフィール
フッター -up-> 検索

' ブログ
公開ブログ一覧 --> ブログ詳細: ブログ選択
非公開ブログ一覧 --> ブログ詳細: ブログ選択
ブログ詳細 --> 公開ブログ一覧: 戻る
ブログ詳細 --> 非公開ブログ一覧: 戻る
ブログ詳細 --> ブログ編集: 編集
ブログ詳細 --> ブログ詳細: おすすめのブログ
ブログ作成 --> ブログ詳細: 成功
ブログ作成 --> ブログ作成: 失敗
ブログ編集 --> ブログ詳細: 成功
ブログ編集 --> ブログ編集: 失敗

' 検索からの遷移
検索 -up-> ブログ
検索 -up-> プロフィール
検索 -up-> Chat

@enduml