services:
  web: 
    build: 
      context: ./
      dockerfile: .dockerfile
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - .env:/var/www/.env
  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
